# 异步编程

## 概念 、JS 执行分析

正常JS中会将整个script的代码全部同步运行后，统一渲染

同步阻塞现象，上面的代码没有结束，则后续代码是无法执行的



异步不会阻塞

就相当于一个在执行不是异步的，一个在执行异步的



进程：简单理解就是（正在运行中的程序，提供一个程序执行的内存环境）

线程 ：在进程中真正执行任务的这个人（干活的【单线程， 多线程】）



同步：程序执行路径只有唯一的一条（一个人在干活）

异步:可以同时有多条路径来执行(多个人同时干活，谁干谁的活，互不干扰)





每写一个异步就会让浏览器创建一个事件线程

浏览器会为每一个节点事件都开启一个独立的线程来处理

我们的**浏览器是多线程**的，但是我们的**JS引擎是单线程**的

每个浏览器主要包含以下多线程：

1. GUI 渲染线程（给浏览器画画用的 DOM / BOM）
2. **JS引擎线程** (主要用于解析JS代码，默认是单线程的【H5中提供了一个web workers 来实现JS的多线程】)
3. **浏览器事件线程**（通过DOM绑定的一些事件 onclick...）
4. **定时器触发线程**（setInterval，setTimeout）
5. **http 异步线程**（ajax请求）
6. **EventLoop（事件循环）处理线程** （主要用于处理异步代码执行顺序

##  回调解决异步

ES6前都是通过回调函数来解决异步调用问题

```javascript
function test(aa){
    setTimeout(function(){
        $.ajax({
            url：xxx，
            dataType:"json",
            success(res){
            aa(res)
        }
        })
    },1000)
}

使用回调函数的方法来处理异步任务执行后的结果
test(function(data){
    console.log(data)
})
```

## 回调地狱

- 什么是回调地狱 ？
  - 回调函数嵌套调用，外部回调函数异步执行的结果是嵌套回调函数的条件
- 回调地狱的缺点
  - 可读性很差
  - 不便于异常处理
  - 后期维护差
- - 

```javascript
需求：每隔1s打印：aaaa,bbbb,cccc
setTimeout(function(){
    console.log('aaa')
    setTimeout(function(){
    console.log('bbb')
        setTimeout(function(){
    console.log('ccc')
},1000)
},1000)
},1000)
回调地狱：回调函数在嵌套使用时，可能会出现这种回调地狱问题

```

如何解决回调地狱问题？

- ES6 提供 **Promise** 链式调用解决回调地狱问题（封装了异步任务的函数）
- ES7 优化了Promise，提供了**async / await** (语法糖) 【终极解决方案】

## Promise

### 2.1 简介

- Promise 是一门新的ES6规范，是JS中用来**解决异步编程**的新的解决方案（曾经使用回调函数解决）

- Promise 从语法层面上来说 ： Promise本质就是一个构造函数，可以new

- Promise 从功能上来说： Promise对象可以封装一个异步操作，并且可以获取到异步任务执行成功/失败时的结果

总结 ：Promise 是ES6引入的异步编程的新的解决方案，从语法层面上来说是一个构造函数，可以new来得到实例化对象。从功能上来说，它可以封装异步操作，获取异步任务执行成功或失败的结果。它的优点是：**支持链式调用，可以解决回调地狱问题**，比回调函数处理异步任务更加灵活

### 创建Promise对象语法

Promise主要是用于封装异步代码

当异步任务执行成功时，我们可以通过resolve（数据）来传递出成功后的返回结果

当异步任务执行失败时，我们可以通过reject（错误原因）来返回失败的原因

```javascript
new Promise(function(resolve,rejext){})
new Promise((resolve,reject)=>{})

let pro = new Promise(function(resolve,reject){
	当创建Peomise对象时，内部的执行器函数会议同步的方式来执行
    resolve("成功的数据")返回成功的结果
    reject("失败了")
})



构造函数： Promise(excutor)
    excutor函数 ： 执行器函数 （resolve，reject） => {}
    resolve函数 ：当内部任务定义成功时，我们需要调用的函数resolve()
    reject函数 ：当内部任务定义失败时，我们需要调用的函数reject()
```



成功后使用then（）接收成功后的结果

失败后用catch（）捕获Promise任务执行失败后的原因





```javascript
let promise = new Promise((resolve,reject)=>{
    异步代码
    任务成功 resolve()
    任务失败 reject()
})
promise.then().catch()





```



Promise内部的代码是按照同步顺序来执行的

```javascript

let pro = new Promise((resolve,reject)=>{
    console.log(111)
    setTimeout(function(){
        let msg = '定时器执行后的结果'
        console.log(msg)
        resolve(msg)//将异步执行后的结果保存在Promise对象中
    },2000)
    console.log(2222)
})
Promise内部的代码是按照同步顺序来执行的
。then（）才是真正的异步代码
pro.then(function(data){
    console.log(data)
})
```



在日常使用

```javascript
 function xx(data) {
       return  new Promise((resolve, reject)=>{
            setTimeout(function () {
                resolve(data)
            },2000)
        })
    }
    xx('111').then(item=>{
        console.log(item)
        return xx('bbb')
    }).then(item=>{
        console.log(item)
    })
```

也可以在匿名函数中使用

## async/await

async/await 是 ES6 后为了进一步优化Promise写法，推出的一种更加简单的异步编程写法，使得我们的异步编程更加简单，更加方便。

因此，我们把 async 、 await 称之为Promise的语法糖



###  async、await

- 主要用来修饰函数 ： **async** 函数 ( ) { }不是异步
- 当使用 async 修饰函数时，函数的返回值默认就是 Promise对象
- Promise对象的结果由async函数的返回值决定



**<font color='red'>只能接收成功的数据，不能接受失败的结果如果有错误的会报错</font>**

需要有报错的方式可以在放在try ...catch里面





**<font color='red'>主要解决Promise的调用问题</font>**

await 执行Promise执行resolve（）后的结果，

错误了直接报错

```javascript
会同步阻塞
async function f(){
    let data1 = await axios.get('xxx')
     let data2 = await axios.get('bbb')
     let arr = [data1,data2]
     console.log(arr)第一种直接调用
     return arr 第二种可以将一些复杂的异步业务逻辑封装在一起，同一来处理
}
f()第一种


第二种
f().then(item=>{
	console.log(item)
})
```

写的时候用Promise

用的时候可以await



**<font color='red'>在await后面的都是异步的代码</font>**

跟在.then()里一样，要是await后再一个await就是回调地狱



看起来简洁方便

```javascript


```





### try...catch

在函数内部如果出错就会导致整个程序终止，我们可以使用try。。。cat

```javascript
async function f (){
    try{
        xxxxx
    }catch(e){
        console.log('请求失败')
    }
    
}
```

